version: '3.4'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    links: []
    ports:
      - "50200:80"
    volumes:
      - ./var/log/nginx:/var/log/nginx
    restart: always

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
      - ./var/log/express:/var/log/express
    restart: always
    depends_on: []
    links:
      - api
    ports:
      - "3000"
    environment:
      - HOST=0.0.0.0
    command: "yarn dev"
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api/
      - ./var/log/express:/var/log/express
    restart: always
    depends_on: []
    links:
      - mysql
    ports:
      - "3000"
    environment:
      - HOST=0.0.0.0
    env_file: ./.env
    command: "yarn dev"
    stdin_open: true
    tty: true

  mysql:
    image: mysql
    links: []
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment: {}
    env_file: ./.env

networks:
  default:
    external:
      name: animeshi
