version: '3.4'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
      - /app/node_modules
    restart: always
    depends_on: []
    links: []
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    command: yarn dev
    stdin_open: true
    tty: true
